app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from app.models import Customer


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class ReportForm(FlaskForm):
    summary = StringField('Job Description', validators=[DataRequired()])
    action = TextAreaField('Action Taken', validators=[DataRequired()])
    recommendation = TextAreaField('Recommendations')
    submit = SubmitField('Submit Report')

class CustomerForm(FlaskForm):
    name = StringField('Customer Name', validators=[DataRequired()])
    notes = StringField('Notes')
    submit = SubmitField('Ok')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user
from app import db
from app.main import bp
from app.main.forms import ReportForm, CustomerForm
from app.models import User, Customer, Report

@bp.route('/')
@bp.route('/index')
@login_required
def index():
    reports = Report.query.filter_by(user_id=current_user.id)
    users = User.query.all()
    customers = Customer.query.all()
    return render_template('main/index.html',
                           reports=reports, 
                           users=users,
                           customers=customers)


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=user)


@bp.route('/customer/<int:id>')
@login_required
def customer(id):
    customer = Customer.query.filter_by(id=id).first_or_404()
    return render_template('main/customer.html', customer=customer)


#todo: figure out how to pass the current customer to the route.
@bp.route('/update_customer/<int:id>', methods=['GET','POST'])
@login_required
def update_customer(id):
    customer = Customer.query.filter_by(id=id).first_or_404()
    form = CustomerForm()
    if request.method == 'GET':
        form.name.data = customer.getName()
        form.notes.data = customer.getNotes()
    if form.validate_on_submit():
        customer.setName(form.name.data)
        customer.setNotes(form.notes.data)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('main/update_customer.html', 
                           customer=customer,
                           form=form)


@bp.route('/create_report', methods=['GET', 'POST'])
@login_required
def create_report():
    form = ReportForm()
    if form.validate_on_submit():
        report = Report(author=current_user, 
                        customer=Customer.query.first_or_404(),
                        summary=form.summary.data,
                        action=form.action.data,
                        recommendation = form.recommendation.data)
        db.session.add(report)
        db.session.commit()
        flash('Your report has been recorded!')
        return redirect(url_for('auth.login'))
    return render_template('main/create_report.html', 
                           title='Create Report',
                           form=form)


@bp.route('/create_customer', methods=['GET', 'POST'])
@login_required
def create_customer():
    form = CustomerForm()
    if form.validate_on_submit():
        #todo: check for uniqueness
        customer = Customer()
        customer.setName(form.name.data)
        customer.setNotes(form.notes.data)
        db.session.add(customer)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('main/create_customer.html',
                           title='Create New Customer',
                           form=form)


@bp.route('/report/<int:id>')
@login_required
def report(id):
    report = Report.query.filter_by(id=id).first_or_404()
    return render_template('main/report.html', report = report)


@bp.route('/update_report/<int:id>', methods=['GET', 'POST'])
@login_required
def update_report(id):
    report = Report.query.filter_by(id=id).first_or_404()
    form = ReportForm()
    if request.method == 'GET':
        form.summary.data = report.getSummary()
        form.action.data = report.getAction()
        form.recommendation.data = report.getRecommendation()
    if form.validate_on_submit():
        report.setSummary(form.summary.data)
        report.setAction(form.action.data)
        report.setRecommendation(form.recommendation.data)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('main/update_report.html', 
                           title='Update Report',
                           report = report,
                           form=form)

app/templates/main/create_customer.html
{% extends "base.html" %}
{% block content %}
    <h1>Create Customer</h1>
        <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}<br>
            {% for error in form.name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.notes.label }}<br>
            {{ form.notes(size=64) }}<br>
            {% for error in form.notes.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
       <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/main/create_report.html
{% extends "base.html" %}
{% block content %}
    <h1>Job Report</h1>
        <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.summary.label }}<br>
            {{ form.summary(size=64) }}<br>
            {% for error in form.summary.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.action.label }}<br>
            {{ form.action(cols=64, rows=6) }}<br>
            {% for error in form.action.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.recommendation.label }}<br>
            {{ form.recommendation(cols=64, rows=4) }}<br>
            {% for error in form.recommendation.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/main/customer.html
{% extends "base.html" %}

{% block content %}
    <h1>Customer: {{ customer.customer_name }}</h1>
    <h2>{{customer.customer_notes }}</h2>
    <a href="{{url_for('main.update_customer',id = customer.id)}}">Update</a>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% block content %}
    <h1>All Users</h1>
    {% for user in users %}
        <a href="{{ url_for('main.user', username=user.getName()) }}">{{ user.getName() }}</a><br>
    {% endfor %}
    <h1>All Customers</h1>
    {% for customer in customers %}
        <a href="{{ url_for('main.customer', id=customer.id) }}">
        {{ customer.getName()}}</a><br>
    {% endfor %}
    <br>
    <a href="{{ url_for('main.create_customer') }}">Create New Customer</a><br>
    <h1>Hi, {{current_user.username}}!</h1>
    {% for report in reports %}
        {% include '_report.html' %}<br>
    {% endfor %}
    <a href="{{ url_for('main.create_report') }}">Write a New Report</a>
{% endblock %}

app/templates/main/report.html
{% extends "base.html" %}
{% block content %}
{% include '_report.html' %}
{% endblock %}

app/templates/main/update_customer.html
{% extends "base.html" %}
{% block content %}
    <h1>Update Customer</h1>
        <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}<br>
            {% for error in form.name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.notes.label }}<br>
            {{ form.notes(size=64) }}<br>
            {% for error in form.notes.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
       <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/main/update_report.html
{% extends "base.html" %}
{% block content %}
    <h1>Update Report</h1>
        <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.summary.label }}<br>
            {{ form.summary(size=64) }}<br>
            {% for error in form.summary.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.action.label }}<br>
            {{ form.action(size=64) }}<br>
            {% for error in form.action.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.recommendation.label }}<br>
            {{ form.recommendation(size=64) }}<br>
            {% for error in form.recommendation.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}